# Generated by Django 4.0.3 on 2022-03-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_date'),
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(related_name='product', through='sales.Sale_detail', to='products.product'),
        ),
    ]
