# Generated by Django 4.0.3 on 2022-03-14 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='products',
        ),
    ]
