# Generated by Django 4.0.3 on 2022-03-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_price'),
        ('sales', '0004_remove_sale_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(related_name='product', through='sales.Sale_detail', to='products.product'),
        ),
    ]
