# Generated by Django 4.0.3 on 2022-03-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LP', 'Laptops'), ('VG', 'Video games'), ('CL', 'Clothing'), ('OT', 'Others')], max_length=20),
        ),
    ]
