# Generated by Django 4.0.3 on 2022-03-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LP', 'Laptops'), ('CG', 'Console games'), ('CP', 'Cell Phones'), ('CA', 'Camera'), ('CL', 'Clothing'), ('OT', 'Others')], max_length=20),
        ),
    ]
