# Generated by Django 4.0.3 on 2022-03-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Tec', 'Tecnologia'), ('Ropa', 'Ropa'), ('Gaming', 'Gaming'), ('Otros', 'Otros')], max_length=20),
        ),
    ]
